
name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: labtest
          template: ./infra/templates/create_new_envt.bicep
          # parameters: storageAccountType=Standard_LRS
 
        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
