name: GitHub Environments

on:
  workflow_dispatch:

environment: 
  name: production
  url: https://github.com

jobs:
  deployment:
    
    runs-on: ubuntu-latest


      
    steps:
      - name: 'Print secret from environment'
        run: |
            echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"