name: 'Passing Values to Next Jobs'

on:  workflow_dispatch

jobs:

  job1:
    runs-on: windows-latest
    
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - id: step1
        run: echo "::set-output name=test::ImportantValue1"
      - id: step2
        run: echo "::set-output name=test::ImportantValue2"
  
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Printing the values"
          echo output1: ${{needs.job1.outputs.output1}}
          echo output2: ${{needs.job1.outputs.output2}}
