# This is a workflow to demonstarte self hosted runner job processing

name: 'self hosted runner demo'

on: workflow_dispatch

jobs:
  sayHello:
    runs-on: [self-hosted, Windows, X64, gpu]
    steps: 
    - name: runscript-to-say-hello
      run:  echo "Howdy GitHub Actions"
    - name: sleep for 100 seconds
      run: sleep 100
