name: Environment Variables Example

on:
  push:

jobs:
  example_job:
    runs-on: ubuntu-latest

    environment: uat

    steps:
      - name: Access Environment Variable
        run: |
          echo "My Environment Variable: ${{ env.MY_VARIABLE }}"
          echo "My Environment Variable: $MY_VARIABLE"
