
name: Environment Variables Example

on:
  push:

jobs:
  example_job:
    runs-on: ubuntu-latest

    environment: uat

    steps:
      - name: Access Environment Variable
        run: |
          printenv
          echo "AZURE_WEBAPP_PUBLISH_PROFILE_DOCKER: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOCKER  }}"
          echo "AZURE_WEBAPP_PUdedeR: ${{ secrets.AZURE_WEBAPP_PUBLIddeR  }}"
          echo "My Environment Variable: $MY_VARIABLE"
          echo "My Environment Variable: ${{ secrets.MY_VARIABLE }}"
