
name: Environment Variables Example

on:
  push:

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Access Environment Variable
        run: |
          echo "AZURE_WEBAPP_PUBLISH_PROFILE_DOCKER: ${{secrets.SEC}}"
          echo "My Environment Variable: ${{secrets.TEST}}"
          echo "My Environment Variable: ${{env.TEST}}"
          echo "My Environment Variable: ${{vars.MY_VARIABLE}}"
          printenv
