# A workflow that uses the if conditional to check if the github.ref 
# (the branch or tag ref that triggered the workflow run) matches 
# refs/heads/main in order to proceed with the following steps in the 
# workflow would look something like this:

name: Conditional StatementVIJAY

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        type: string
  
env:
  test: Vijay

jobs:
  prod-check:
    name: run-job-if-condition-is-satisfied
    
    runs-on: ubuntu-latest
    steps:

    - name: step-name1
      if: ${{ inputs.tags }} 
      run: echo "I am executed"

    - name: step-name2
      if: ${{ env.test2 }} 
      run: echo "I am executed"
